version: "3.0"
services:
  virtualhost:
    container_name: python_virtualhost
    build:
      context: ./docker/virtualhost
      args:
        PYTHON_VER: ${PYTHON_VERSION}
        SSH_PORT: ${VIRTUAL_HOST_SSH_PORT}
        PERSONAL_ACCESS_TOKEN: ${PERSONAL_ACCESS_TOKEN}
    environment:
      - TZ=Asia/Tokyo
    # NOTE: env_file is not necessary if you use only .env as env_file.
    # env_file:
    #   - .env
    ports:
      - ${OPEN_PORT}:${OPEN_PORT}
      - ${VIRTUAL_HOST_SSH_PORT}:${VIRTUAL_HOST_SSH_PORT}
    volumes:
      # Pip modules
      - pip-modules:/usr/local/lib/${PIP_MODULES_DIRECTORY}/site-packages
      # The data for VSCode extension
      - ./volumes/vscode-server:/root/.vscode-server
      # The directory for development
      - ./volumes/opt:/root/lab/opt

      # 各種設定を container へコピー
      - ./conf/.bash_profile:/root/.bash_profile
      - ./conf/gitconfig:/root/.gitconfig:ro

    # NOTE: /user/sbin/sshd -D について
    #   container 起動時に sshd がフォアグラウンドで実行され、ssh ログインできるようになる
    command: bash -c "
        echo \"export PASSWORD=${PASSWORD}\" >> ~/.bashrc
        && . ~/.bash_profile
        && /usr/sbin/sshd -D
      "

volumes:
  pip-modules:
    external:
      name: pip-modules
